//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWDLCondelpi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWDLCondelpi.Service1Soap")]
    public interface Service1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIpSuver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetIpSuverAsync(string key, string equipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutIpSuver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PutIpSuverAsync(string key, string IP, string EQUIPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGIsAuthenticated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> LOGIsAuthenticatedAsync(string key, string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNombRe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetNombReAsync(string key, string identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DENCP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> DENCPAsync(string key, string campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ENCP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ENCPAsync(string key, string campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Time", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.DateTime> TimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Prowl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProwlAsync(string msj, string prioridad, string evento, string url, string keymsj, string Application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataNw", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataNwAsync(string key, string identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getnewcon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetnewconResponse> GetnewconAsync(SWDLCondelpi.GetnewconRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEquifax", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetEquifaxResponse> GetEquifaxAsync(SWDLCondelpi.GetEquifaxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAPC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetAPCResponse> GetAPCAsync(SWDLCondelpi.GetAPCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getdms_pag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.Getdms_pagResponse> Getdms_pagAsync(SWDLCondelpi.Getdms_pagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetAvalResponse> GetAvalAsync(SWDLCondelpi.GetAvalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegsitro_civil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_civilResponseGetRegsitro_civilResult> GetRegsitro_civilAsync(string key, string cedula, string dactilar, string userid, string ip_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegsitro_IMG_FOT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_IMG_FOTResponseGetRegsitro_IMG_FOTResult> GetRegsitro_IMG_FOTAsync(string key, string cedula, string userid, string ip_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegsitro_civil1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_civil1Response> GetRegsitro_civil1Async(SWDLCondelpi.GetRegsitro_civil1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRegsitro_IMG_FOT1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_IMG_FOT1Response> GetRegsitro_IMG_FOT1Async(SWDLCondelpi.GetRegsitro_IMG_FOT1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataAsanbl_Adj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataAsanbl_AdjAsync(string key, string fechaIni, string fechaInf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataRRHH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataRRHHAsync(string key, string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataoferNw", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataoferNwAsync(string key, string gr, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataofertafull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataofertafullAsync(string key, string grupo, string fecha, string fechafin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataoferNwCOMPLE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataoferNwCOMPLEAsync(string key, string gr, string fecha, string fecha1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataNwadj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataNwadjAsync(string key, string identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataasaadjica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataasaadjicaAsync(string key, string fechaasa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataAsync(string key, string identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataFamilia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataFamiliaAsync(string key, string identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataRiesgo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataRiesgoAsync(string key, string identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataplaca", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataplacaAsync(string key, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataiesAsync(string key, string identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getcnt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetcntAsync(string key, string AREA, string numero, string nombre, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RESTARTIIS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> RESTARTIISAsync(string servidor, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PingAsync(string ipOrHostName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PingT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PingTAsync(string ipOrHostName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/join_conect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> join_conectAsync(string paramet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/User_conect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> User_conectAsync(string paramet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/join_DB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> join_DBAsync(string paramet, string IP, string Machine, string so, string tipo, string usuario, string dominio, string logs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Data_Base", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Data_BaseAsync(string paramet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Data_BaseMD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Data_BaseMDAsync(string paramet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sendmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SendmailAsync(string deml, string validacion, string tomail, string descripcion, string asunto, string srv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sendmail1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Sendmail1Async(string validacion, string from, string tomail, string descripcion, string asunto, string srv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearTablaC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task CrearTablaCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Shutrabort", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ShutrabortAsync(string equipo, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Shutreset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ShutresetAsync(string equipo, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Servidores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ServidoresAsync(string key, string servidores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estaciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> EstacionesAsync(string key, string estacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Errores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ErroresAsync(string key, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Key", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> KeyAsync(string key, string consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Codigos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CodigosAsync(string key, string consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Base64Smtp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Base64SmtpAsync(string subject, string body, string tomail, string fromMail, string ccMail, string fileat, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdResetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdResetPasswordAsync(string key, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdDisableUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdDisableUserAsync(string key, string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdUnlookPass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdUnlookPassAsync(string key, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdLookPass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdLookPassAsync(string key, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdcodigoEmpresa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdcodigoEmpresaAsync(string key, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_User_sql", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GET_User_sqlAsync(string key, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdcodigoCi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdcodigoCiAsync(string key, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADconsultLdap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ADconsultLdapAsync(string key, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdChangePasswordAsync(string key, string userName, string newPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdIsExistInAd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AdIsExistInAdAsync(string key, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdGetUserPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.AdGetUserPictureResponse> AdGetUserPictureAsync(SWDLCondelpi.AdGetUserPictureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataplacasrent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataplacasrentAsync(string key, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataclienterent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataclienterentAsync(string key, string nit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getusados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetusadosAsync(string key, string marca, string modelo, string anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CotizadorApc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> CotizadorApcAsync(string key, string NOMBRE1, string NOMBRE2, string APELLIDO1, string APELLIDO2, string CEDULA, string TELEFONO, string MAIL, System.DateTime FECHA_REGISTRO, int TIPCLI_CODIGO, int ID_PLAN, int Monto, int REFERIDO, string RELACION_REF, int COD_REGIONAL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOG_LOGIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> LOG_LOGINAsync(string key, string Aplicacion, string Usuario, string Equipo, string Tipo, string Descripcion, int error);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ArrayOfDataTableDataTable
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Getnewcon", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetnewconRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedula;
        
        public GetnewconRequest()
        {
        }
        
        public GetnewconRequest(string key, string cedula)
        {
            this.key = key;
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetnewconResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetnewconResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public SWDLCondelpi.ArrayOfDataTableDataTable[] GetnewconResult;
        
        public GetnewconResponse()
        {
        }
        
        public GetnewconResponse(SWDLCondelpi.ArrayOfDataTableDataTable[] GetnewconResult)
        {
            this.GetnewconResult = GetnewconResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEquifax", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEquifaxRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ip_data;
        
        public GetEquifaxRequest()
        {
        }
        
        public GetEquifaxRequest(string key, string cedula, string userid, string ip_data)
        {
            this.key = key;
            this.cedula = cedula;
            this.userid = userid;
            this.ip_data = ip_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEquifaxResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEquifaxResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public SWDLCondelpi.ArrayOfDataTableDataTable[] GetEquifaxResult;
        
        public GetEquifaxResponse()
        {
        }
        
        public GetEquifaxResponse(SWDLCondelpi.ArrayOfDataTableDataTable[] GetEquifaxResult)
        {
            this.GetEquifaxResult = GetEquifaxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAPC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAPCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedula;
        
        public GetAPCRequest()
        {
        }
        
        public GetAPCRequest(string key, string cedula)
        {
            this.key = key;
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAPCResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAPCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public SWDLCondelpi.ArrayOfDataTableDataTable[] GetAPCResult;
        
        public GetAPCResponse()
        {
        }
        
        public GetAPCResponse(SWDLCondelpi.ArrayOfDataTableDataTable[] GetAPCResult)
        {
            this.GetAPCResult = GetAPCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Getdms_pag", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Getdms_pagRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string datos;
        
        public Getdms_pagRequest()
        {
        }
        
        public Getdms_pagRequest(string key, string datos)
        {
            this.key = key;
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Getdms_pagResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Getdms_pagResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public SWDLCondelpi.ArrayOfDataTableDataTable[] Getdms_pagResult;
        
        public Getdms_pagResponse()
        {
        }
        
        public Getdms_pagResponse(SWDLCondelpi.ArrayOfDataTableDataTable[] Getdms_pagResult)
        {
            this.Getdms_pagResult = Getdms_pagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAval", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAvalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ip_data;
        
        public GetAvalRequest()
        {
        }
        
        public GetAvalRequest(string key, string cedula, string userid, string ip_data)
        {
            this.key = key;
            this.cedula = cedula;
            this.userid = userid;
            this.ip_data = ip_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAvalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public SWDLCondelpi.ArrayOfDataTableDataTable[] GetAvalResult;
        
        public GetAvalResponse()
        {
        }
        
        public GetAvalResponse(SWDLCondelpi.ArrayOfDataTableDataTable[] GetAvalResult)
        {
            this.GetAvalResult = GetAvalResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetRegsitro_civilResponseGetRegsitro_civilResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetRegsitro_IMG_FOTResponseGetRegsitro_IMG_FOTResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRegsitro_civil1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRegsitro_civil1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dactilar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ip_data;
        
        public GetRegsitro_civil1Request()
        {
        }
        
        public GetRegsitro_civil1Request(string key, string cedula, string dactilar, string userid, string ip_data)
        {
            this.key = key;
            this.cedula = cedula;
            this.dactilar = dactilar;
            this.userid = userid;
            this.ip_data = ip_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRegsitro_civil1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRegsitro_civil1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public SWDLCondelpi.ArrayOfDataTableDataTable[] GetRegsitro_civil1Result;
        
        public GetRegsitro_civil1Response()
        {
        }
        
        public GetRegsitro_civil1Response(SWDLCondelpi.ArrayOfDataTableDataTable[] GetRegsitro_civil1Result)
        {
            this.GetRegsitro_civil1Result = GetRegsitro_civil1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRegsitro_IMG_FOT1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRegsitro_IMG_FOT1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ip_data;
        
        public GetRegsitro_IMG_FOT1Request()
        {
        }
        
        public GetRegsitro_IMG_FOT1Request(string key, string cedula, string userid, string ip_data)
        {
            this.key = key;
            this.cedula = cedula;
            this.userid = userid;
            this.ip_data = ip_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRegsitro_IMG_FOT1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRegsitro_IMG_FOT1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public SWDLCondelpi.ArrayOfDataTableDataTable[] GetRegsitro_IMG_FOT1Result;
        
        public GetRegsitro_IMG_FOT1Response()
        {
        }
        
        public GetRegsitro_IMG_FOT1Response(SWDLCondelpi.ArrayOfDataTableDataTable[] GetRegsitro_IMG_FOT1Result)
        {
            this.GetRegsitro_IMG_FOT1Result = GetRegsitro_IMG_FOT1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdGetUserPicture", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdGetUserPictureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string usuario;
        
        public AdGetUserPictureRequest()
        {
        }
        
        public AdGetUserPictureRequest(string key, string usuario)
        {
            this.key = key;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdGetUserPictureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdGetUserPictureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] AdGetUserPictureResult;
        
        public AdGetUserPictureResponse()
        {
        }
        
        public AdGetUserPictureResponse(byte[] AdGetUserPictureResult)
        {
            this.AdGetUserPictureResult = AdGetUserPictureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface Service1SoapChannel : SWDLCondelpi.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<SWDLCondelpi.Service1Soap>, SWDLCondelpi.Service1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetIpSuverAsync(string key, string equipo)
        {
            return base.Channel.GetIpSuverAsync(key, equipo);
        }
        
        public System.Threading.Tasks.Task<string> PutIpSuverAsync(string key, string IP, string EQUIPO)
        {
            return base.Channel.PutIpSuverAsync(key, IP, EQUIPO);
        }
        
        public System.Threading.Tasks.Task<bool> LOGIsAuthenticatedAsync(string key, string username, string pwd)
        {
            return base.Channel.LOGIsAuthenticatedAsync(key, username, pwd);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetNombReAsync(string key, string identidad)
        {
            return base.Channel.GetNombReAsync(key, identidad);
        }
        
        public System.Threading.Tasks.Task<string> DENCPAsync(string key, string campo)
        {
            return base.Channel.DENCPAsync(key, campo);
        }
        
        public System.Threading.Tasks.Task<string> ENCPAsync(string key, string campo)
        {
            return base.Channel.ENCPAsync(key, campo);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> TimeAsync()
        {
            return base.Channel.TimeAsync();
        }
        
        public System.Threading.Tasks.Task<string> ProwlAsync(string msj, string prioridad, string evento, string url, string keymsj, string Application)
        {
            return base.Channel.ProwlAsync(msj, prioridad, evento, url, keymsj, Application);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataNwAsync(string key, string identidad)
        {
            return base.Channel.GetDataNwAsync(key, identidad);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetnewconResponse> SWDLCondelpi.Service1Soap.GetnewconAsync(SWDLCondelpi.GetnewconRequest request)
        {
            return base.Channel.GetnewconAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.GetnewconResponse> GetnewconAsync(string key, string cedula)
        {
            SWDLCondelpi.GetnewconRequest inValue = new SWDLCondelpi.GetnewconRequest();
            inValue.key = key;
            inValue.cedula = cedula;
            return ((SWDLCondelpi.Service1Soap)(this)).GetnewconAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetEquifaxResponse> SWDLCondelpi.Service1Soap.GetEquifaxAsync(SWDLCondelpi.GetEquifaxRequest request)
        {
            return base.Channel.GetEquifaxAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.GetEquifaxResponse> GetEquifaxAsync(string key, string cedula, string userid, string ip_data)
        {
            SWDLCondelpi.GetEquifaxRequest inValue = new SWDLCondelpi.GetEquifaxRequest();
            inValue.key = key;
            inValue.cedula = cedula;
            inValue.userid = userid;
            inValue.ip_data = ip_data;
            return ((SWDLCondelpi.Service1Soap)(this)).GetEquifaxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetAPCResponse> SWDLCondelpi.Service1Soap.GetAPCAsync(SWDLCondelpi.GetAPCRequest request)
        {
            return base.Channel.GetAPCAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.GetAPCResponse> GetAPCAsync(string key, string cedula)
        {
            SWDLCondelpi.GetAPCRequest inValue = new SWDLCondelpi.GetAPCRequest();
            inValue.key = key;
            inValue.cedula = cedula;
            return ((SWDLCondelpi.Service1Soap)(this)).GetAPCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWDLCondelpi.Getdms_pagResponse> SWDLCondelpi.Service1Soap.Getdms_pagAsync(SWDLCondelpi.Getdms_pagRequest request)
        {
            return base.Channel.Getdms_pagAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.Getdms_pagResponse> Getdms_pagAsync(string key, string datos)
        {
            SWDLCondelpi.Getdms_pagRequest inValue = new SWDLCondelpi.Getdms_pagRequest();
            inValue.key = key;
            inValue.datos = datos;
            return ((SWDLCondelpi.Service1Soap)(this)).Getdms_pagAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetAvalResponse> SWDLCondelpi.Service1Soap.GetAvalAsync(SWDLCondelpi.GetAvalRequest request)
        {
            return base.Channel.GetAvalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.GetAvalResponse> GetAvalAsync(string key, string cedula, string userid, string ip_data)
        {
            SWDLCondelpi.GetAvalRequest inValue = new SWDLCondelpi.GetAvalRequest();
            inValue.key = key;
            inValue.cedula = cedula;
            inValue.userid = userid;
            inValue.ip_data = ip_data;
            return ((SWDLCondelpi.Service1Soap)(this)).GetAvalAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_civilResponseGetRegsitro_civilResult> GetRegsitro_civilAsync(string key, string cedula, string dactilar, string userid, string ip_data)
        {
            return base.Channel.GetRegsitro_civilAsync(key, cedula, dactilar, userid, ip_data);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_IMG_FOTResponseGetRegsitro_IMG_FOTResult> GetRegsitro_IMG_FOTAsync(string key, string cedula, string userid, string ip_data)
        {
            return base.Channel.GetRegsitro_IMG_FOTAsync(key, cedula, userid, ip_data);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_civil1Response> SWDLCondelpi.Service1Soap.GetRegsitro_civil1Async(SWDLCondelpi.GetRegsitro_civil1Request request)
        {
            return base.Channel.GetRegsitro_civil1Async(request);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_civil1Response> GetRegsitro_civil1Async(string key, string cedula, string dactilar, string userid, string ip_data)
        {
            SWDLCondelpi.GetRegsitro_civil1Request inValue = new SWDLCondelpi.GetRegsitro_civil1Request();
            inValue.key = key;
            inValue.cedula = cedula;
            inValue.dactilar = dactilar;
            inValue.userid = userid;
            inValue.ip_data = ip_data;
            return ((SWDLCondelpi.Service1Soap)(this)).GetRegsitro_civil1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_IMG_FOT1Response> SWDLCondelpi.Service1Soap.GetRegsitro_IMG_FOT1Async(SWDLCondelpi.GetRegsitro_IMG_FOT1Request request)
        {
            return base.Channel.GetRegsitro_IMG_FOT1Async(request);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.GetRegsitro_IMG_FOT1Response> GetRegsitro_IMG_FOT1Async(string key, string cedula, string userid, string ip_data)
        {
            SWDLCondelpi.GetRegsitro_IMG_FOT1Request inValue = new SWDLCondelpi.GetRegsitro_IMG_FOT1Request();
            inValue.key = key;
            inValue.cedula = cedula;
            inValue.userid = userid;
            inValue.ip_data = ip_data;
            return ((SWDLCondelpi.Service1Soap)(this)).GetRegsitro_IMG_FOT1Async(inValue);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataAsanbl_AdjAsync(string key, string fechaIni, string fechaInf)
        {
            return base.Channel.GetDataAsanbl_AdjAsync(key, fechaIni, fechaInf);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataRRHHAsync(string key, string cedula)
        {
            return base.Channel.GetDataRRHHAsync(key, cedula);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataoferNwAsync(string key, string gr, string fecha)
        {
            return base.Channel.GetDataoferNwAsync(key, gr, fecha);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataofertafullAsync(string key, string grupo, string fecha, string fechafin)
        {
            return base.Channel.GetDataofertafullAsync(key, grupo, fecha, fechafin);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataoferNwCOMPLEAsync(string key, string gr, string fecha, string fecha1)
        {
            return base.Channel.GetDataoferNwCOMPLEAsync(key, gr, fecha, fecha1);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataNwadjAsync(string key, string identidad)
        {
            return base.Channel.GetDataNwadjAsync(key, identidad);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataasaadjicaAsync(string key, string fechaasa)
        {
            return base.Channel.GetDataasaadjicaAsync(key, fechaasa);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataAsync(string key, string identidad)
        {
            return base.Channel.GetDataAsync(key, identidad);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataFamiliaAsync(string key, string identidad)
        {
            return base.Channel.GetDataFamiliaAsync(key, identidad);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataRiesgoAsync(string key, string identidad)
        {
            return base.Channel.GetDataRiesgoAsync(key, identidad);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataplacaAsync(string key, string placa)
        {
            return base.Channel.GetDataplacaAsync(key, placa);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataiesAsync(string key, string identidad)
        {
            return base.Channel.GetDataiesAsync(key, identidad);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetcntAsync(string key, string AREA, string numero, string nombre, string direccion)
        {
            return base.Channel.GetcntAsync(key, AREA, numero, nombre, direccion);
        }
        
        public System.Threading.Tasks.Task<string> RESTARTIISAsync(string servidor, string key)
        {
            return base.Channel.RESTARTIISAsync(servidor, key);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string ipOrHostName)
        {
            return base.Channel.PingAsync(ipOrHostName);
        }
        
        public System.Threading.Tasks.Task<string> PingTAsync(string ipOrHostName)
        {
            return base.Channel.PingTAsync(ipOrHostName);
        }
        
        public System.Threading.Tasks.Task<string> join_conectAsync(string paramet)
        {
            return base.Channel.join_conectAsync(paramet);
        }
        
        public System.Threading.Tasks.Task<string> User_conectAsync(string paramet)
        {
            return base.Channel.User_conectAsync(paramet);
        }
        
        public System.Threading.Tasks.Task<string> join_DBAsync(string paramet, string IP, string Machine, string so, string tipo, string usuario, string dominio, string logs)
        {
            return base.Channel.join_DBAsync(paramet, IP, Machine, so, tipo, usuario, dominio, logs);
        }
        
        public System.Threading.Tasks.Task<string> Data_BaseAsync(string paramet)
        {
            return base.Channel.Data_BaseAsync(paramet);
        }
        
        public System.Threading.Tasks.Task<string> Data_BaseMDAsync(string paramet)
        {
            return base.Channel.Data_BaseMDAsync(paramet);
        }
        
        public System.Threading.Tasks.Task<string> SendmailAsync(string deml, string validacion, string tomail, string descripcion, string asunto, string srv)
        {
            return base.Channel.SendmailAsync(deml, validacion, tomail, descripcion, asunto, srv);
        }
        
        public System.Threading.Tasks.Task<string> Sendmail1Async(string validacion, string from, string tomail, string descripcion, string asunto, string srv)
        {
            return base.Channel.Sendmail1Async(validacion, from, tomail, descripcion, asunto, srv);
        }
        
        public System.Threading.Tasks.Task CrearTablaCAsync()
        {
            return base.Channel.CrearTablaCAsync();
        }
        
        public System.Threading.Tasks.Task<string> ShutrabortAsync(string equipo, string key)
        {
            return base.Channel.ShutrabortAsync(equipo, key);
        }
        
        public System.Threading.Tasks.Task<string> ShutresetAsync(string equipo, string key)
        {
            return base.Channel.ShutresetAsync(equipo, key);
        }
        
        public System.Threading.Tasks.Task<string> ServidoresAsync(string key, string servidores)
        {
            return base.Channel.ServidoresAsync(key, servidores);
        }
        
        public System.Threading.Tasks.Task<string> EstacionesAsync(string key, string estacion)
        {
            return base.Channel.EstacionesAsync(key, estacion);
        }
        
        public System.Threading.Tasks.Task<string> ErroresAsync(string key, string error)
        {
            return base.Channel.ErroresAsync(key, error);
        }
        
        public System.Threading.Tasks.Task<string> KeyAsync(string key, string consulta)
        {
            return base.Channel.KeyAsync(key, consulta);
        }
        
        public System.Threading.Tasks.Task<string> CodigosAsync(string key, string consulta)
        {
            return base.Channel.CodigosAsync(key, consulta);
        }
        
        public System.Threading.Tasks.Task<string> Base64SmtpAsync(string subject, string body, string tomail, string fromMail, string ccMail, string fileat, string tipo)
        {
            return base.Channel.Base64SmtpAsync(subject, body, tomail, fromMail, ccMail, fileat, tipo);
        }
        
        public System.Threading.Tasks.Task<string> AdResetPasswordAsync(string key, string usuario)
        {
            return base.Channel.AdResetPasswordAsync(key, usuario);
        }
        
        public System.Threading.Tasks.Task<string> AdDisableUserAsync(string key, string cuenta)
        {
            return base.Channel.AdDisableUserAsync(key, cuenta);
        }
        
        public System.Threading.Tasks.Task<string> AdUnlookPassAsync(string key, string usuario)
        {
            return base.Channel.AdUnlookPassAsync(key, usuario);
        }
        
        public System.Threading.Tasks.Task<string> AdLookPassAsync(string key, string usuario)
        {
            return base.Channel.AdLookPassAsync(key, usuario);
        }
        
        public System.Threading.Tasks.Task<string> AdcodigoEmpresaAsync(string key, string usuario)
        {
            return base.Channel.AdcodigoEmpresaAsync(key, usuario);
        }
        
        public System.Threading.Tasks.Task<string> GET_User_sqlAsync(string key, string usuario)
        {
            return base.Channel.GET_User_sqlAsync(key, usuario);
        }
        
        public System.Threading.Tasks.Task<string> AdcodigoCiAsync(string key, string usuario)
        {
            return base.Channel.AdcodigoCiAsync(key, usuario);
        }
        
        public System.Threading.Tasks.Task<string> ADconsultLdapAsync(string key, string usuario)
        {
            return base.Channel.ADconsultLdapAsync(key, usuario);
        }
        
        public System.Threading.Tasks.Task<string> AdChangePasswordAsync(string key, string userName, string newPass)
        {
            return base.Channel.AdChangePasswordAsync(key, userName, newPass);
        }
        
        public System.Threading.Tasks.Task<string> AdIsExistInAdAsync(string key, string usuario)
        {
            return base.Channel.AdIsExistInAdAsync(key, usuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SWDLCondelpi.AdGetUserPictureResponse> SWDLCondelpi.Service1Soap.AdGetUserPictureAsync(SWDLCondelpi.AdGetUserPictureRequest request)
        {
            return base.Channel.AdGetUserPictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.AdGetUserPictureResponse> AdGetUserPictureAsync(string key, string usuario)
        {
            SWDLCondelpi.AdGetUserPictureRequest inValue = new SWDLCondelpi.AdGetUserPictureRequest();
            inValue.key = key;
            inValue.usuario = usuario;
            return ((SWDLCondelpi.Service1Soap)(this)).AdGetUserPictureAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataplacasrentAsync(string key, string placa)
        {
            return base.Channel.GetDataplacasrentAsync(key, placa);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetDataclienterentAsync(string key, string nit)
        {
            return base.Channel.GetDataclienterentAsync(key, nit);
        }
        
        public System.Threading.Tasks.Task<SWDLCondelpi.ArrayOfXElement> GetusadosAsync(string key, string marca, string modelo, string anio)
        {
            return base.Channel.GetusadosAsync(key, marca, modelo, anio);
        }
        
        public System.Threading.Tasks.Task<bool> CotizadorApcAsync(string key, string NOMBRE1, string NOMBRE2, string APELLIDO1, string APELLIDO2, string CEDULA, string TELEFONO, string MAIL, System.DateTime FECHA_REGISTRO, int TIPCLI_CODIGO, int ID_PLAN, int Monto, int REFERIDO, string RELACION_REF, int COD_REGIONAL)
        {
            return base.Channel.CotizadorApcAsync(key, NOMBRE1, NOMBRE2, APELLIDO1, APELLIDO2, CEDULA, TELEFONO, MAIL, FECHA_REGISTRO, TIPCLI_CODIGO, ID_PLAN, Monto, REFERIDO, RELACION_REF, COD_REGIONAL);
        }
        
        public System.Threading.Tasks.Task<bool> LOG_LOGINAsync(string key, string Aplicacion, string Usuario, string Equipo, string Tipo, string Descripcion, int error)
        {
            return base.Channel.LOG_LOGINAsync(key, Aplicacion, Usuario, Equipo, Tipo, Descripcion, error);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.condelpi.com/ActviveDirectory/service1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.condelpi.com/ActviveDirectory/service1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.1")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
