//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSIturan
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSIturan.OnlineSoap")]
    public interface OnlineSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSIturan.GetCarsInfoResponse> GetCarsInfoAsync(WSIturan.GetCarsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfoNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSIturan.GetCarsInfoNewResponse> GetCarsInfoNewAsync(WSIturan.GetCarsInfoNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarsInfoNewByGroupName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSIturan.GetCarsInfoNewByGroupNameResponse> GetCarsInfoNewByGroupNameAsync(WSIturan.GetCarsInfoNewByGroupNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> AuthenticateAsync(string Username, string Password, string CompanyName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginInfo
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string companyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CarOnlinePosItemInfo
    {
        
        private decimal vehicle_LatitudeField;
        
        private decimal vehicle_LongitudeField;
        
        private short vehicle_AngleField;
        
        private short vehicle_ColorField;
        
        private string vehicle_Tool_TipField;
        
        private string vehicle_LabelField;
        
        private byte vehicle_Drive_typeField;
        
        private string event_TimeField;
        
        private byte vehicle_Online_StatusField;
        
        private string rEGION_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Vehicle_Latitude
        {
            get
            {
                return this.vehicle_LatitudeField;
            }
            set
            {
                this.vehicle_LatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Vehicle_Longitude
        {
            get
            {
                return this.vehicle_LongitudeField;
            }
            set
            {
                this.vehicle_LongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short Vehicle_Angle
        {
            get
            {
                return this.vehicle_AngleField;
            }
            set
            {
                this.vehicle_AngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short Vehicle_Color
        {
            get
            {
                return this.vehicle_ColorField;
            }
            set
            {
                this.vehicle_ColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Vehicle_Tool_Tip
        {
            get
            {
                return this.vehicle_Tool_TipField;
            }
            set
            {
                this.vehicle_Tool_TipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Vehicle_Label
        {
            get
            {
                return this.vehicle_LabelField;
            }
            set
            {
                this.vehicle_LabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte Vehicle_Drive_type
        {
            get
            {
                return this.vehicle_Drive_typeField;
            }
            set
            {
                this.vehicle_Drive_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Event_Time
        {
            get
            {
                return this.event_TimeField;
            }
            set
            {
                this.event_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public byte Vehicle_Online_Status
        {
            get
            {
                return this.vehicle_Online_StatusField;
            }
            set
            {
                this.vehicle_Online_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string REGION_NAME
        {
            get
            {
                return this.rEGION_NAMEField;
            }
            set
            {
                this.rEGION_NAMEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSIturan.LoginInfo LoginInfo;
        
        public GetCarsInfoRequest()
        {
        }
        
        public GetCarsInfoRequest(WSIturan.LoginInfo LoginInfo)
        {
            this.LoginInfo = LoginInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WSIturan.CarOnlinePosItemInfo[] GetCarsInfoResult;
        
        public GetCarsInfoResponse()
        {
        }
        
        public GetCarsInfoResponse(WSIturan.CarOnlinePosItemInfo[] GetCarsInfoResult)
        {
            this.GetCarsInfoResult = GetCarsInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoNew", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoNewRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSIturan.LoginInfo LoginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DeviceID;
        
        public GetCarsInfoNewRequest()
        {
        }
        
        public GetCarsInfoNewRequest(WSIturan.LoginInfo LoginInfo, string DeviceID)
        {
            this.LoginInfo = LoginInfo;
            this.DeviceID = DeviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoNewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoNewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCarsInfoNewResult;
        
        public GetCarsInfoNewResponse()
        {
        }
        
        public GetCarsInfoNewResponse(string GetCarsInfoNewResult)
        {
            this.GetCarsInfoNewResult = GetCarsInfoNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoNewByGroupName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoNewByGroupNameRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSIturan.LoginInfo LoginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OriginIP;
        
        public GetCarsInfoNewByGroupNameRequest()
        {
        }
        
        public GetCarsInfoNewByGroupNameRequest(WSIturan.LoginInfo LoginInfo, string GroupName, string OriginIP)
        {
            this.LoginInfo = LoginInfo;
            this.GroupName = GroupName;
            this.OriginIP = OriginIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsInfoNewByGroupNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsInfoNewByGroupNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCarsInfoNewByGroupNameResult;
        
        public GetCarsInfoNewByGroupNameResponse()
        {
        }
        
        public GetCarsInfoNewByGroupNameResponse(string GetCarsInfoNewByGroupNameResult)
        {
            this.GetCarsInfoNewByGroupNameResult = GetCarsInfoNewByGroupNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface OnlineSoapChannel : WSIturan.OnlineSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OnlineSoapClient : System.ServiceModel.ClientBase<WSIturan.OnlineSoap>, WSIturan.OnlineSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OnlineSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OnlineSoapClient.GetBindingForEndpoint(endpointConfiguration), OnlineSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OnlineSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OnlineSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSIturan.GetCarsInfoResponse> WSIturan.OnlineSoap.GetCarsInfoAsync(WSIturan.GetCarsInfoRequest request)
        {
            return base.Channel.GetCarsInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSIturan.GetCarsInfoResponse> GetCarsInfoAsync(WSIturan.LoginInfo LoginInfo)
        {
            WSIturan.GetCarsInfoRequest inValue = new WSIturan.GetCarsInfoRequest();
            inValue.LoginInfo = LoginInfo;
            return ((WSIturan.OnlineSoap)(this)).GetCarsInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSIturan.GetCarsInfoNewResponse> WSIturan.OnlineSoap.GetCarsInfoNewAsync(WSIturan.GetCarsInfoNewRequest request)
        {
            return base.Channel.GetCarsInfoNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSIturan.GetCarsInfoNewResponse> GetCarsInfoNewAsync(WSIturan.LoginInfo LoginInfo, string DeviceID)
        {
            WSIturan.GetCarsInfoNewRequest inValue = new WSIturan.GetCarsInfoNewRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.DeviceID = DeviceID;
            return ((WSIturan.OnlineSoap)(this)).GetCarsInfoNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSIturan.GetCarsInfoNewByGroupNameResponse> WSIturan.OnlineSoap.GetCarsInfoNewByGroupNameAsync(WSIturan.GetCarsInfoNewByGroupNameRequest request)
        {
            return base.Channel.GetCarsInfoNewByGroupNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSIturan.GetCarsInfoNewByGroupNameResponse> GetCarsInfoNewByGroupNameAsync(WSIturan.LoginInfo LoginInfo, string GroupName, string OriginIP)
        {
            WSIturan.GetCarsInfoNewByGroupNameRequest inValue = new WSIturan.GetCarsInfoNewByGroupNameRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.GroupName = GroupName;
            inValue.OriginIP = OriginIP;
            return ((WSIturan.OnlineSoap)(this)).GetCarsInfoNewByGroupNameAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateAsync(string Username, string Password, string CompanyName)
        {
            return base.Channel.AuthenticateAsync(Username, Password, CompanyName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OnlineSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OnlineSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OnlineSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.worldfleetlog.com/WebFleetStationServices/Online.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OnlineSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.worldfleetlog.com/WebFleetStationServices/Online.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OnlineSoap,
            
            OnlineSoap12,
        }
    }
}
